---
title: "fstest_2realdata_1003"
author: "Zihan Zhu"
date: "2023-10-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Basic functions

run all the functions

```{r}
library(amap)
library(ggpubr)
library(rstatix)
km_cluster <- function(X) { 
  km <- Kmeans(X, 2, iter.max = 100, nstart=10)#,method = "manhattan")
  return(km$cluster)
}

hi_cluster <- function(X, meth =  "ward.D") {
  hc <- hclust(dist(X), meth)
  return(cutree(hc, k = 2))
}

sd_cluster <- function(X) {
  sd <- pam(X, 2)
  return(sd$clustering)
}
```

```{r}
# function to compute the selective type I error

test_clusters_approx_tensor <- function(X, k1, k2, iso=TRUE, sig=NULL, SigInv=NULL, ndraws=2000, cl_fun, cl=NULL) {
  if(!is.matrix(X)) stop("X should be a matrix")
  n <- nrow(X)
  q <- ncol(X)
  
  if(is.null(cl)) cl <- cl_fun(X)
  K <- length(unique(cl))
  
  if(!is_integer_between_a_b(K, 2, n)) stop("number of clusters (K) should be between 2 and n")
  if(!is_integer_between_a_b(k1, 1, K) | !is_integer_between_a_b(k2, 1, K)) stop(paste("cluster indices should be between 1 and K", sep=""))
  if((iso != TRUE) & (iso != FALSE)) stop("iso should be TRUE or FALSE")
  
  n1 <- sum(cl == k1)
  n2 <- sum(cl == k2)
  squared_norm_nu <- 1/n1 + 1/n2
  diff_means <- colMeans(X[cl == k1, , drop=FALSE]) - colMeans(X[cl == k2, , drop=F])
  
  prop_k2 <- n2/(n1+n2)
  
  
  if(iso) {
    if(is.null(sig)) {
      sig <- sqrt(sum(scale(X, scale=FALSE)^2)/(n*q - q))
    }
    
    scale_factor <- squared_norm_nu*sig^2
    # compute test statistic
    stat <- norm_vec(diff_means)
  } else {
    if(is.null(SigInv)) {
      Sig <- stats::cov(scale(X, scale=FALSE))
      SigInv <- solve(Sig)
    }

    scale_factor <- squared_norm_nu
    
    # compute test statistic
    stat <- sqrt(as.numeric(t(diff_means)%*%SigInv%*%diff_means))
  }
  
  scale_factor <- sqrt(scale_factor)
  phi <- stats::rnorm(ndraws)*scale_factor + stat
  
  
  k1_constant <- prop_k2*diff_means#/stat
  k2_constant <- (prop_k2 - 1)*diff_means#/stat
  orig_k1 <- t(X[cl == k1, ])
  orig_k2 <- t(X[cl == k2, ])
  
  Xphi <- X
  
  log_survives <- unlist(future.apply::future_lapply(X = 1:ndraws, FUN = function(j) {
    if(phi[j] < 0) return(NA)
    
    # Compute perturbed data set
    Xphi <- X
    Xphi[cl == k1, ] <- t(orig_k1 + (phi[j] - stat)*k1_constant)
    Xphi[cl == k2, ] <- t(orig_k2 + (phi[j] - stat)*k2_constant)
    
    # Recluster the perturbed data set
    cl_Xphi <- cl_fun(Xphi)
    if(preserve_cl(cl, cl_Xphi, k1, k2)) {
      log_survives <- -(phi[j]/scale_factor)^2/2 + (q-1)*log(phi[j]/scale_factor) - (q/2 - 1)*log(2) - lgamma(q/2) - log(scale_factor) -
        stats::dnorm(phi[j], mean=stat, sd=scale_factor, log=TRUE)
      return(log_survives)
    }
    
    return(NA)
    
  }, future.seed=TRUE))
  
  # Trim down to only survives
  phi <- phi[!is.na(log_survives)]
  log_survives <- log_survives[!is.na(log_survives)]
  
  survives <- length(log_survives)
  
  # Return nothing if nothing survives
  if(survives == 0) {
    warning("Oops - we didn't generate any samples that preserved the clusters! Try re-running with a larger value of ndraws.")
    return(list(stat=stat, pval=NA, stderr=NA, clusters=cl))
  }
  
  #  Approximate p-values
  log_survives_shift <- log_survives - max(log_survives)
  props <- exp(log_survives_shift)/sum(exp(log_survives_shift))
  pval <- sum(props[phi >= stat])

  var_pval <- (1 - pval)^2*sum(props[phi >= stat]^2) + pval^2*sum(props[phi < stat]^2)
  
  return(list(stat=stat, pval=pval, stderr=sqrt(var_pval), clusters=cl, n_survive = survives, phi = phi,prop = props,log_survive = log_survives))
}

```

```{r}
# ----- general purpose helper functions -----

norm_vec <- function(x) {
  sqrt(sum(x^2))
}

is_integer_between_a_b <- function(x, a, b) {
  (x>= min(c(a, b))) && (x %% 1 == 0) && (x <= max(c(a, b)))
}

same_cl <- function(cl1, cl2, K) {
  tab <- table(cl1, cl2)
  sum(tab != 0) == K
}

preserve_cl <- function(cl, cl_phi, k1, k2) {
  tab <- table(cl, cl_phi)
  
  k1_in <- (sum(tab[k1, ] != 0) == 1) & (sum(tab[, k1] != 0) == 1)
  k2_in <- (sum(tab[k2, ] != 0) == 1) & (sum(tab[, k2] != 0) == 1)

  k1_in & k2_in
}
```

```{r}
multivariate_Z_test <- function(X, k1, k2) { 
  q <- ncol(X)
  hcl <- sd_cluster(X)
  
  diff_means <- colMeans(X[hcl == k1, , drop=F]) - colMeans(X[hcl == k2, , drop=F])
  stat <- norm_vec(diff_means) 
  n1 <- sum(hcl == k1)  
  n2 <- sum(hcl == k2) 
  squared_norm_nu <- 1/n1 + 1/n2
  scale_factor <- squared_norm_nu
  
  pval <- 1 - pchisq(stat^2/scale_factor, df=q)
  return(list(stat=stat, pval=pval))
}
```

# set parameters

```{r, warning=FALSE}
#import library and set parameters
library(cluster)
library(MASS)
library(EQL)
library(e1071)
library(ggplot2)
library(gogarch)
library(tmvtnorm)
library(expm)
library(matrixStats)
library(matrixNormal)

rho = 0.95#0.993
lambd = 10^(-7)
day = 30#14
seed = 3600*24*120

#trun = 8

rho1 = 0.5
#m = nrow(dat_mat)/2 #number of patients
m = 10000
p = 3 #number of features
X = seq(0,3600*24*120,1)/3600*24*120
K = length(X)
alpha = 0.5
beta = 0.5
deca = matrix(rep(1,K*K),K,K)
for(i in seq(K)){
  for( j in seq(K)){
    u = max(i,j)
    v = min(i,j)
    if (u<=2*K/3 & v>K/3) deca[i,j] = (K-u)/(K+1)
    else deca[i,j] = 0.01
  }
}

kernel = function(X, rho = rho, K){
  sqdist = (matrix(rep(X,K),K,K)-t(matrix(rep(X,K),K,K)))^2
  return(exp(-rho / (1-rho^2) * sqdist))
}

kernel_rq = function(X1, X2, rho = rho1,alpha = alpha){
  sqdist = (matrix(rep(X,K),K,K)-t(matrix(rep(X,K),K,K)))^2
  return((1+rho/(1-rho^2)/alpha*sqdist)^(-alpha))
}
kernel_per = function(X1, X2, rho = rho1,beta = beta){
  sindist = sin(pi*abs(matrix(rep(X,K),K,K)-t(matrix(rep(X,K),K,K)))/beta)^2
  return(exp(-2*sindist*rho/(1-rho^2)))
}
kernel_lpe = function(X1, X2, rho = rho1,beta = beta){
  dist = 2*sin(pi*abs(matrix(rep(X,K),K,K)-t(matrix(rep(X,K),K,K)))/beta)^2+(matrix(rep(X,K),K,K)-t(matrix(rep(X,K),K,K)))^2/2
  return(exp(-dist*rho/(1-rho^2)))
}
f = function(i,x){
  r = rep(0,length(x))
  N = 2^i*sqrt((1-rho)/(1+rho))*factorial(i)
  for(j in seq(length(x))){
    r[j] = exp(-rho/(1+rho)*x[j]^2)*hermite(x[j],i,prob = FALSE)/sqrt(N)
  }
  return(r)
}

mu = rep(0,K)
cov = kernel(X, rho, K)
cov_rq = kernel_rq(X,X,rho1,alpha)
cov_per = kernel_per(X,X,rho1,beta)
cov_lpe = kernel_lpe(X,X,rho1,beta)
tsam = mvrnorm(m, mu, deca*cov)

time = seq(0,1,1/(K-1))
kernel_f = matrix(rep(0,p*K),p,K)
for(i in seq(p)){
  kernel_f[i,] = f(i-1,time)
}

eigen = c()
for(i in seq(p)){
  eigen = c(eigen, (1-rho)*rho**(i-1))
}
core_mat = diag(eigen)
```

# import dataset

```{r}
library(readr)
Sub_ID_SC_CATEGORY_sepsis_4 <- readRDS("C:/Users/11132/Documents/R files/Sub_ID_SC_CATEGORY_sepsis_4.rds")
lab_drg_870_872_filtered_Feb_iv <- read_csv("C:/Users/11132/Documents/R files/lab_diabetes_E109_Sep_iv(1).csv")

codat = merge(Sub_ID_SC_CATEGORY_sepsis_4, lab_drg_870_872_filtered_Feb_iv, by = "SUBJECT_ID")
codat = na.omit(codat)
codat$VALUE = as.numeric(codat$VALUE)

s1 = codat[codat$SC_CATEGORY == "S1",]
s2 = codat[codat$SC_CATEGORY == "S2",]
s3 = codat[codat$SC_CATEGORY == "S3",]

s4 = codat[codat$SC_CATEGORY == "S4",]
s5 = codat[codat$SC_CATEGORY == "S5",]

s1 = na.omit(read_csv("C:/Users/11132/Documents/R files/lab_diabetes_E109_Sep_iv(1).csv"))
s2 = na.omit(read_csv("C:/Users/11132/Documents/R files/lab_diabetes_E119_Sep_iv(1).csv"))

s1$VALUE = as.numeric(s1$VALUE)
s2$VALUE = as.numeric(s2$VALUE)

d1 = read_csv("C:/Users/11132/Documents/R files/lab_diabetes_E109_Sep_iv(1).csv")
d2 = read_csv("C:/Users/11132/Documents/R files/lab_diabetes_E119_Sep_iv(1).csv")


age = d1[d1$FEATURE_NAME == 'Age',]
fea1 = d1[d1$FEATURE_NAME == '% Hemoglobin A1c',]
fea2 = d2[d2$FEATURE_NAME == '% Hemoglobin A1c',]
fea3 = d1[d1$FEATURE_NAME == 'Daily Weight',]
fea4 = d1[d1$FEATURE_NAME == 'Height',]
fea5 = d2[d2$FEATURE_NAME == 'Daily Weight',]
fea6 = d2[d2$FEATURE_NAME == 'Height',]
id1 = unique(fea1$SUBJECT_ID)
id2 = unique(fea2$SUBJECT_ID)

age1 = c()
for(i in 1:nrow(age)){
  if(any(age[i,1] == id1)) age1 = c(age1, age[i,4])
}

age1

d1$VALUE <- as.numeric(gsub("\\[([0-9]+)\\]", "\\1", d1$VALUE))
d2$VALUE <- as.numeric(gsub("\\[([0-9]+)\\]", "\\1", d2$VALUE))

colMeans(d1[d1$FEATURE_NAME == 'Age',4])
colMeans(d2[d2$FEATURE_NAME == 'Age',4])

fd1 = d1[which(d1$SUBJECT_ID %in% unique(fea1$SUBJECT_ID)),]
fd2 = d2[which(d2$SUBJECT_ID %in% unique(fea2$SUBJECT_ID)),]

colMeans(fd1[fd1$FEATURE_NAME == 'Age',4])
colMeans(fd2[fd2$FEATURE_NAME == 'Age',4])

a0 = c(fd1[fd1$FEATURE_NAME == 'Age',4]$VALUE,fd2[fd2$FEATURE_NAME == 'Age',4]$VALUE)
la0 = c(rep(2,length(fd1[fd1$FEATURE_NAME == 'Age',4]$VALUE)),rep(3,length(fd2[fd2$FEATURE_NAME == 'Age',4]$VALUE)))
fd = data.frame(a0 = a0, la0 = la0)

ggplot(fd) + geom_boxplot(aes(x = as.factor(la0),y = a0,fill = as.factor(la0))) + xlab('S1 vs S2') + ylab('Age') + theme_bw()

fd1
```

```{r}
set.seed(seed)

# set the day and truncate the dataset for three groups

trun = 3
#c('% Hemoglobin A1c','INR(PT)','Lactate')
multis1 = s1[s1$FEATURE_NAME == c('% Hemoglobin A1c'),]
d7multis1 = multis1[multis1$RECORD_MIN<=3600*24*60,]
d7multis1 = na.omit(d7multis1)

multis2 = s2[s2$FEATURE_NAME == c('% Hemoglobin A1c'),]
d7multis2 = multis2[multis2$RECORD_MIN<=3600*24*60,]
d7multis2 = na.omit(d7multis2)

ag1 = c()
ag2 = c()

feature = c('% Hemoglobin A1c')
dattol = rbind(d7multis1)
length(unique(d7multis1[d7multis1$FEATURE_NAME == feature[1],]$SUBJECT_ID))

pred = list()
idsam = data.frame(c(unique(dattol[dattol$FEATURE_NAME == feature[1],]$SUBJECT_ID)))
names(idsam) = 'ICUID'

rect1 = list()
recv1 = list()

for(fea in feature){
  print(fea)
  datcur = dattol[dattol$FEATURE_NAME == fea,]
  m = length(unique(datcur$SUBJECT_ID))
  cursam = c()
  ida = 0
  
  for(id in 1:m){
    dcur = datcur[datcur$SUBJECT_ID == unique(datcur$SUBJECT_ID)[id],]
    K = length(dcur$RECORD_MIN)
    if(K <= trun) next
    #ag1 = c(ag1,fd1[fd1$SUBJECT_ID == unique(datcur$SUBJECT_ID)[id] & fd1$FEATURE_NAME == 'Age',4]$VALUE)
    ida = ida+1
    time = dcur$RECORD_MIN/(3600*24*120)
    val = as.matrix(dcur$VALUE)
    #val = log(val/val[1])
    
    rect1[[ida]] = time
    recv1[[ida]] = val
    
    kercur = kernel(time,rho,K)
    kernel_f = matrix(rep(0,p*K),p,K)
    for(i in seq(p)){
      kernel_f[i,] = f(i-1,time)
    }
    mat1 = t(kernel_f)%*%core_mat
    inv1 = solve(kercur+lambd*diag(K))
  
    coef = t(val)%*%inv1
    if(anyNA(val)){
      print(val)
    }
    
    pred[[ida]] = coef%*%kercur
    #cursam = c(cursam, unique(datcur$SUBJECT_ID)[id],coef%*%mat1)
    cursam = c(cursam, unique(datcur$SUBJECT_ID)[id],t(val)%*%t(solve(kernel_f%*%t(kernel_f)+lambd*diag(p))%*%kernel_f))#solve(t(kernel_f)%*%kernel_f+lambd*diag(K))%*%t(kernel_f))
  }
  cursam = t(array(cursam, dim = c(p+1, ida)))
  datf = data.frame(cursam)
  names(datf)[1] = 'ICUID'
  idsam = merge(idsam,datf, by = 'ICUID')
}

tol_sam1 = na.omit(as.matrix(idsam[,-1]))

dattol = rbind(d7multis2)

idsam = data.frame(c(unique(dattol[dattol$FEATURE_NAME == feature[1],]$SUBJECT_ID)))
names(idsam) = 'ICUID'

rect2 = list()
recv2 = list()

for(fea in feature){
  print(fea)
  datcur = dattol[dattol$FEATURE_NAME == fea,]
  m = length(unique(datcur$SUBJECT_ID))
  cursam = c()
  ida = 0
  
  for(id in 1:m){
    dcur = datcur[datcur$SUBJECT_ID == unique(datcur$SUBJECT_ID)[id],]
    K = length(dcur$RECORD_MIN)
    if(K <= trun) next
    #ag2 = c(ag2,fd2[fd2$SUBJECT_ID == unique(datcur$SUBJECT_ID)[id] & fd2$FEATURE_NAME == 'Age',4]$VALUE)
    ida = ida+1
    time = dcur$RECORD_MIN/(3600*24*120)
    val = as.matrix(dcur$VALUE)
    #val = log(val/val[1])
    
    rect2[[ida]] = time
    recv2[[ida]] = val
    
    kercur = kernel(time,rho,K)
    kernel_f = matrix(rep(0,p*K),p,K)
    for(i in seq(p)){
      kernel_f[i,] = f(i-1,time)
    }
    #mat1 = t(kernel_f)%*%core_mat
    #inv1 = solve(kercur+lambd*diag(K))

    #coef = t(val)%*%inv1
    if(anyNA(val)){
      print(val)
    }
    
    #cursam = c(cursam, unique(datcur$SUBJECT_ID)[id],coef%*%mat1)
    cursam = c(cursam, unique(datcur$SUBJECT_ID)[id],t(val)%*%t(solve(kernel_f%*%t(kernel_f)+lambd*diag(p))%*%kernel_f))#solve(t(kernel_f)%*%kernel_f+lambd*diag(K))%*%t(kernel_f))
  }
  cursam = t(array(cursam, dim = c(p+1, ida)))
  datf = data.frame(cursam)
  names(datf)[1] = 'ICUID'
  idsam = merge(idsam,datf, by = 'ICUID')
}

tol_sam2 = na.omit(as.matrix(idsam[,-1]))


tol_sam1 = tol_sam1[,-4]
tol_sam2 = tol_sam2[,-4]

tol_sam1 = cbind(tol_sam1, ag1)
tol_sam2 = cbind(tol_sam2, ag2)
```

```{r, warning = FALSE}
set.seed(seed)
sam_cov1 = solve(Re(sqrtm(cov(tol_sam1))))
whit_samp1 = tol_sam1%*%sam_cov1
cl = hi_cluster(whit_samp1)

# compute the selective p-value

time = Sys.time()
pva = test_clusters_approx_tensor(whit_samp1, k1=1, k2=2, cl_fun = hi_cluster, cl = cl, ndraws=20000)
Sys.time()-time
#pval = c(pval,pva$pval)
print(pva$pval)

# compute the p-value by the classical way
t.test(whit_samp1[cl == 1],whit_samp1[cl == 2])
```

```{r, warning = FALSE}
sam_cov2 = solve(Re(sqrtm(cov(tol_sam2))))
whit_samp2 = tol_sam2%*%sam_cov2
cl = hi_cluster(whit_samp2)

# compute the selective p-value

time = Sys.time()
pva = test_clusters_approx_tensor(whit_samp2, k1=1, k2=2, cl_fun=hi_cluster, cl = cl, ndraws=20000)
Sys.time()-time
#pval = c(pval,pva$pval)
print(pva$pval)

# compute the p-value by the classical way
t.test(whit_samp2[cl == 1],whit_samp2[cl == 2])
```

```{r, warning = FALSE}

sam_cov3 = solve(Re(sqrtm(cov(tol_sam3))))
whit_samp3 = tol_sam3%*%sam_cov3
cl = hi_cluster(whit_samp3)

# compute the selective p-value

time = Sys.time()
pva = test_clusters_approx_tensor(whit_samp3, k1=1, k2=2, cl_fun=hi_cluster, cl = cl, ndraws=20000)
Sys.time()-time
#pval = c(pval,pva$pval)
print(pva$pval)

# compute the p-value by the classical way
t.test(whit_samp3[cl == 1],whit_samp3[cl == 2])
```

```{r, warning = FALSE}
tol_sam12 = rbind(tol_sam1, tol_sam2)

sam_cov12 = solve(Re(sqrtm(cov(tol_sam12))))
whit_samp12 = tol_sam12%*%sam_cov12
cl = hi_cluster(whit_samp12)

# compute the selective p-value

time = Sys.time()
pva = test_clusters_approx_tensor(whit_samp12, k1=1, k2=2, cl_fun=hi_cluster, cl = cl, ndraws=6000)
Sys.time()-time
#pval = c(pval,pva$pval)
print(pva$pval)

# compute the p-value by the classical way
t.test(whit_samp12[cl == 1],whit_samp12[cl == 2])
```

```{r, warning = FALSE}
tol_sam13 = rbind(tol_sam1, tol_sam3)

sam_cov13 = solve(Re(sqrtm(cov(tol_sam13))))
whit_samp13 = tol_sam13%*%sam_cov13
cl = hi_cluster(whit_samp13)

# compute the selective p-value

time = Sys.time()
pva = test_clusters_approx_tensor(whit_samp13, k1=1, k2=2, cl_fun=hi_cluster, cl = cl, ndraws=6000)
Sys.time()-time
#pval = c(pval,pva$pval)
print(pva$pval)

# compute the p-value by the classical way
t.test(whit_samp13[cl == 1],whit_samp13[cl == 2])
```

```{r, warning = FALSE}
tol_sam23 = rbind(tol_sam2, tol_sam3)

sam_cov23 = solve(Re(sqrtm(cov(tol_sam23))))
whit_samp23 = tol_sam23%*%sam_cov23
cl = hi_cluster(whit_samp23)

# compute the selective p-value

time = Sys.time()
pva = test_clusters_approx_tensor(whit_samp23, k1=1, k2=2, cl_fun=hi_cluster, cl = cl, ndraws=6000)
Sys.time()-time
#pval = c(pval,pva$pval)
print(pva$pval)

# compute the p-value by the classical way
t.test(whit_samp23[cl == 1],whit_samp23[cl == 2])
```

```{r, warning = FALSE}
seed = 230
set.seed(seed)
tol_sam14 = rbind(tol_sam1, tol_sam4)

sam_cov14 = solve(Re(sqrtm(cov(tol_sam14))))
whit_samp14 = tol_sam14%*%sam_cov14
cl = hi_cluster(whit_samp14)

# compute the selective p-value

time = Sys.time()
pva = test_clusters_approx_tensor(whit_samp14, k1=1, k2=2, cl_fun=hi_cluster, cl = cl, ndraws=15000)
Sys.time()-time
#pval = c(pval,pva$pval)
print(pva$pval)

# compute the p-value by the classical way
t.test(whit_samp14[cl == 1],whit_samp14[cl == 2])
```

```{r, warning = FALSE}
set.seed(seed)
tol_sam24 = rbind(tol_sam2, tol_sam4)

sam_cov24 = solve(Re(sqrtm(cov(tol_sam24))))
whit_samp24 = tol_sam24%*%sam_cov24
cl = hi_cluster(whit_samp24)

# compute the selective p-value

time = Sys.time()
pva = test_clusters_approx_tensor(whit_samp24, k1=1, k2=2, cl_fun=hi_cluster, cl = cl, ndraws=20000)
Sys.time()-time
#pval = c(pval,pva$pval)
print(pva$pval)

# compute the p-value by the classical way
t.test(whit_samp24[1:nrow(tol_sam2),],whit_samp24[(nrow(tol_sam2)+1):nrow(tol_sam24),])
```

```{r, warning = FALSE}
set.seed(seed)
tol_sam34 = rbind(tol_sam3, tol_sam4)

sam_cov34 = solve(Re(sqrtm(cov(tol_sam34))))
whit_samp34 = tol_sam34%*%sam_cov34
cl = hi_cluster(whit_samp34)

# compute the selective p-value

time = Sys.time()
pva = test_clusters_approx_tensor(whit_samp34, k1=1, k2=2, cl_fun=hi_cluster, cl = cl, ndraws=20000)
Sys.time()-time
#pval = c(pval,pva$pval)
print(pva$pval)

# compute the p-value by the classical way
t.test(whit_samp34[1:nrow(tol_sam3),],whit_samp34[(nrow(tol_sam3)+1):nrow(tol_sam34),])
```

```{r, warning = FALSE}
set.seed(seed)
tol_sam15 = rbind(tol_sam1, tol_sam5)

sam_cov15 = solve(Re(sqrtm(cov(tol_sam15))))
whit_samp15 = tol_sam15%*%sam_cov15
cl = hi_cluster(whit_samp15)

# compute the selective p-value

time = Sys.time()
pva = test_clusters_approx_tensor(whit_samp15, k1=1, k2=2, cl_fun=hi_cluster, cl = cl, ndraws=20000)
Sys.time()-time
#pval = c(pval,pva$pval)
print(pva$pval)

# compute the p-value by the classical way
t.test(whit_samp15[cl == 1],whit_samp15[cl == 2])
```

```{r, warning = FALSE}
set.seed(seed)
tol_sam25 = rbind(tol_sam2, tol_sam5)

sam_cov25 = solve(Re(sqrtm(cov(tol_sam25))))
whit_samp25 = tol_sam25%*%sam_cov25
cl = hi_cluster(whit_samp25)

# compute the selective p-value

time = Sys.time()
pva = test_clusters_approx_tensor(whit_samp25, k1=1, k2=2, cl_fun=hi_cluster, cl = cl, ndraws=20000)
Sys.time()-time
#pval = c(pval,pva$pval)
print(pva$pval)

# compute the p-value by the classical way
t.test(whit_samp25[cl == 1],whit_samp25[cl == 2])
```

```{r, warning = FALSE}
set.seed(seed)
tol_sam35 = rbind(tol_sam3, tol_sam5)

sam_cov35 = solve(Re(sqrtm(cov(tol_sam35))))
whit_samp35 = tol_sam35%*%sam_cov35
cl = hi_cluster(whit_samp35)

# compute the selective p-value

time = Sys.time()
pva = test_clusters_approx_tensor(whit_samp35, k1=1, k2=2, cl_fun=hi_cluster, cl = cl, ndraws=20000)
Sys.time()-time
#pval = c(pval,pva$pval)
print(pva$pval)

# compute the p-value by the classical way
t.test(whit_samp35[cl == 1],whit_samp35[cl == 2])
```

```{r, warning = FALSE}
set.seed(seed)
tol_sam45 = rbind(tol_sam4, tol_sam5)

sam_cov45 = solve(Re(sqrtm(cov(tol_sam45))))
whit_samp45 = tol_sam45%*%sam_cov45
cl = hi_cluster(whit_samp45)

# compute the selective p-value

time = Sys.time()
pva = test_clusters_approx_tensor(whit_samp45, k1=1, k2=2, cl_fun=hi_cluster, cl = cl, ndraws=20000)
Sys.time()-time
#pval = c(pval,pva$pval)
print(pva$pval)

# compute the p-value by the classical way
t.test(whit_samp45[cl == 1],whit_samp45[cl == 2])
```

```{r}
n = 500
m = round(n**(2/3))

sum0 = 0
for(i in 0:round(m/2)){
  sum0 = sum0+choose(n,i)*choose(n-i,m-2*i)
}
sum0/choose(n+m-1,n-1)
```